types:
  definitions:
    default-package: com.achomutovskij.portfolioservice
    objects:
      Configuration:
        fields:
          port: integer
          host: string
          external-api-response-cache-duration-minutes: integer
